### PR TITLE
Let PyPump handle most of the credentials

### PR DESCRIPTION
**Pull request by strugee**
PyPump can keep track of credentials for us, so this patch makes use of that. This means that the workflow is now:

1. Add your username to `PumpTweet.ini`
2. Add Twitter credentials to `PumpTweet.ini`
3. `./pt.py`

As opposed to opening up a Python shell, etc.

### CODE REVIEW

**Comment by strugee** [comment]
I should also point out that this is WIP; please don't merge yet. I just figured I'd share early, to get feedback.

**Comment by strugee** [comment]
All right, I was trying to get PyPump to use a different filesystem path just for us, but I can't quite make it happen. So I'll just say that this is mergeable now.

**Comment by dper** [comment]
I just saw the changes to PyPump but haven't played around with them yet. Does it work well?  Simplifying setup would be nice.

We need the ini file for the Twitter login.  I just checked, and right now python-twitter doesn't have a similar kind of credentials store capability.  In a perfect world, we could push both the pump.io and Twitter logins  to their respective libraries.  Regardless, one is better than zero.  :-)

**Comment by strugee** [comment]
Yeah, I tested it pretty well, and everything looks pretty solid. It works on both the first and second runs (after credentials have been cached), at least in my testing environment. This patch just uses the default Store; we could in theory do a custom one with a proper namespace, but it doesn't really matter, IMHO.

I didn't try with actual Twitter credentials, but those shouldn't matter as long as the client can do auth with Pump.

**Comment by dper** [comment]
Works for me, too. Thanks again. :-)

**Pull request merged**
